### ISSUE TITLE
Long reports HTTPClient timeout configuration for ILocalWebServerReportingService

### ISSUE THREAD

**Issue by thfsilvab** [jsreport/jsreport-dotnet-local#4]
I'm trying to render a big report following the documentation recommendations for big reports [as described here](https://jsreport.net/learn/dotnet-client#timeouts) and [also here](https://jsreport.net/blog/long-reports), `ILocalWebServerReportingService` interface lacks the ability to configure `System.Net..Http.HttpClient` timeout though.

`LocalWebServerReportingService` has the property `ReportingService`, but it's not being exposed by the interface, therefore, I can't increase `System.Net..Http.HttpClient` timeout as recommended by the docs.

This is how my report service is built:
```csharp
var rs = new LocalReporting()
    .UseBinary(JsReportBinary.GetBinary())
    .AsWebServer()
    .Create();
```

I've also tried to increase other timeouts in configuration (I've set up to 2hrs for testing purposes) and Express input size (also 500mb for testing purposes only):
```csharp
var rs = new LocalReporting()
    .UseBinary(JsReportBinary.GetBinary())
    .Configure(config => new Configuration
    {
        Chrome = new ChromeConfiguration
        {
            Timeout = (int)_timeoutMm.TotalMilliseconds
        },
        TemplatingEngines = new TemplatingEnginesConfiguration()
        {
            Timeout = (int)_timeoutMm.TotalMilliseconds
        },
        Extensions = new ExtensionsConfiguration()
        {
            Phantom = new PhantomConfiguration()
            {
                Timeout = (int)_timeoutMm.TotalMilliseconds
            },
            Express = new ExpressConfiguration
            {
                InputRequestLimit = "500mb"
            },
            Scripts = new ScriptsConfiguration()
            {
                Timeout = (int)_timeoutMm.TotalMilliseconds
            }
        }
    })
    .AsWebServer()
    .Create();
```

but still getting `OperationCanceledException: the task was canceled.`.

**Comment by pofider** [comment]
It was exposed in jsreport.Local@2.2.2.
Do you have this version?
https://github.com/jsreport/jsreport-dotnet-local/commit/3046ec3cc11a2f621e09d077cd385c340679ea63

**Comment by thfsilvab** [comment]
Ooops, my bad, I was running v2.1.1
